// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.Models;

[Table("BookAuthor")]
public partial class BookAuthor
{
    [Key]
    public int Id { get; set; }

    [Display(Name = "Livro")]
    public int BookId { get; set; }

    [Display(Name = "Autor")]
    public int AuthorId { get; set; }

    [ForeignKey("AuthorId")]
    [InverseProperty("BookAuthors")]
    [Display(Name = "Autor")]
    public virtual Author Author { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("BookAuthors")]
    [Display(Name = "Livro")]
    public virtual Book Book { get; set; }
}