// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.Models;

[Table("Book")]
[Microsoft.EntityFrameworkCore.Index("Title", Name = "IX_Book_Title")]
public partial class Book
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    [Display(Name = "Título")]
    public string Title { get; set; }

    [Display(Name = "Edição")]
    public int Edition { get; set; }

    [Display(Name = "Ano de publicação")]
    public int? PublicationYear { get; set; }

    [Display(Name = "Volume")]
    public int? Volume { get; set; }

    [Display(Name = "Editora")]
    public int PublisherId { get; set; }

    [Display(Name = "Quantidade de exemplares")]
    public int QuantityAvailable { get; set; }

    [Column("ISBN")]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "ISBN")]
    public string Isbn { get; set; }

    [Column("CDD")]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "CDD")]
    public string Cdd { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    [Display(Name = "Localização na biblioteca")]
    public string LibraryLocation { get; set; }

    [Required]
    [StringLength(450)]
    [Display(Name = "Cadastrado por")]
    public string CreatedByUserId { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Data de cadastro")]
    public DateTime CreatedDate { get; set; }

    [StringLength(450)]
    [Display(Name = "Modificado por")]
    public string ModifiedByUserId { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Última modificação")]
    public DateTime? ModifiedDate { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("Book")]
    [Display(Name = "Autor (es)")]
    public virtual ICollection<BookAuthor> BookAuthors { get; set; } = new List<BookAuthor>();

    [InverseProperty("Book")]
    [Display(Name = "Gênero (s)")]
    public virtual ICollection<BookCategory> BookCategories { get; set; } = new List<BookCategory>();

    [InverseProperty("Book")]
    [Display(Name = "Palavras chaves")]
    public virtual ICollection<BookTag> BookTags { get; set; } = new List<BookTag>();

    [InverseProperty("Book")]
    [Display(Name = "Empréstimos")]
    public virtual ICollection<Loan> Loans { get; set; } = new List<Loan>();

    [ForeignKey("PublisherId")]
    [InverseProperty("Books")]
    [Display(Name = "Editora")]
    public virtual Publisher Publisher { get; set; }

    [StringLength(255)]
    [Display(Name = "Origem")]
    public string Origin { get; set; }

}