// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.Models;

[Table("BookTag")]
[Microsoft.EntityFrameworkCore.Index("BookId", "TagWordId", Name = "UQ_BookTag", IsUnique = true)]
public partial class BookTag
{
    [Key]
    public int Id { get; set; }

    [Display(Name = "Livro")]
    public int BookId { get; set; }

    [Display(Name = "Palavra chave")]
    public int TagWordId { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Data de criação")]
    public DateTime CreatedDate { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("BookTags")]
    [Display(Name = "Livros")]
    public virtual Book Book { get; set; }

    [ForeignKey("TagWordId")]
    [InverseProperty("BookTags")]
    [Display(Name = "Palavra chave")]
    public virtual TagWord TagWord { get; set; }
}