// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.Api.Models;

[Table("BookCategory")]
public partial class BookCategory
{
    [Key]
    public int Id { get; set; }

    [Display(Name = "Livro")]
    public int BookId { get; set; }

    [Display(Name = "Gênero")]
    public int GenreId { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("BookCategories")]
    [Display(Name = "Livro")]
    public virtual Book Book { get; set; }

    [ForeignKey("GenreId")]
    [InverseProperty("BookCategories")]
    [Display(Name = "Gênero")]
    public virtual Category Category { get; set; }
}