// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.api.Models;

[Table("LoanStatus")]
public partial class LoanStatus
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    [Display(Name = "Descrição")]
    public string Description { get; set; }

    [InverseProperty("Status")]
    [Display(Name = "Empréstimos")]
    public virtual ICollection<Loan> Loans { get; set; } = new List<Loan>();
}