// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.api.Models;

[Table("Loan")]
[Microsoft.EntityFrameworkCore.Index("RequesterUserId", Name = "IX_Loan_RequesterUserId")]
public partial class Loan
{
    [Key]
    public int Id { get; set; }


    [Display(Name = "Livro")]
    public int BookId { get; set; }

    [Required]
    [Display(Name = "Leitor")]
    public string RequesterUserId { get; set; }

    [Display(Name = "Status")]
    public int StatusId { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Data de solicitação")]
    public DateTime RequestDate { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Data de retirada")]
    public DateTime? CheckoutDate { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Data de devolução")]
    public DateTime? ReturnDate { get; set; }

    [Column(TypeName = "Prazo para devolução")]
    public DateTime? ExpectedReturnDate { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("Loans")]
    [Display(Name = "Livro")]
    public virtual Book Book { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("Loans")]
    [Display(Name = "Status")]
    public virtual LoanStatus Status { get; set; }

    [ForeignKey("RequesterUserId")]
    [Display(Name = "Leitor")]
    public virtual ApplicationUser RequesterUser { get; set; }

    [StringLength(450)]
    [Display(Name = "Entregue por")]
    public string CheckedOutBy { get; set; }

    [StringLength(450)]
    [Display(Name = "Recebido por")]
    public string ReceivedBy { get; set; }

    [ForeignKey("CheckedOutBy")]
    [Display(Name = "Entregue por")]
    public virtual ApplicationUser EntreguePor { get; set; }

    [ForeignKey("ReceivedBy")]
    [Display(Name = "Recebido por")]
    public virtual ApplicationUser RecebidoPor { get; set; }


}