// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.Models;

[Table("Publisher")]
public partial class Publisher
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    [Display(Name = "Editora")]
    public string Name { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("Publisher")]
    [Display(Name = "Livros")]
    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}