// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.api.Models;

public partial class Setting
{
    [Key]
    public int Id { get; set; }

    [Required]
    [Column("Setting")]
    [StringLength(50)]
    [Display(Name = "Configuração")]
    public string Setting1 { get; set; }

    [Display(Name = "Valor")]
    public int Value { get; set; }
}