// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.Models;

[Microsoft.EntityFrameworkCore.Index("Word", Name = "UQ__TagWords__95B50108BBB35E5F", IsUnique = true)]
public partial class TagWord
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Display(Name = "Palavra chave")]
    public string Word { get; set; }

    [Column(TypeName = "datetime")]
    [Display(Name = "Data de criação")]
    public DateTime CreatedDate { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("TagWord")]
    public virtual ICollection<BookTag> BookTags { get; set; } = new List<BookTag>();
}